### PR TITLE
Don't throw error if tx is not decoded

### PR DESCRIPTION
**Pull request by panleone**
If you cannot decode a tx just return the same tree and an empty vector of nullifier / spent notes

### CODE REVIEW

**Review by Duddino — COMMENTED** [review]
I'm not sure about this, panicking results in an error in JS side, which is what we really want if a tx fails to decode

**Comment by panleone** [comment]
> I'm not sure about this, panicking results in an error in JS side, which is what we really want if a tx fails to decode, we don't want to silently fail in this case

fail = we don't own the corresponding key, which will happen most of the time that function is called

**Comment by Duddino** [comment]
Closing as I can't reproduce in my machine, feel free to reopen if you reencounter this

**Comment by panleone** [comment]
Yep agree I opened because I had this issue before but it must not be related to that

**Pull request closed without merging**
