### PR TITLE
Multicore support

### PR DESCRIPTION
**Pull request by Duddino**
Adds multicore support. The feature will only be enabled if the browser supports it. 
To build with multicore, run the script
`./build_multicore.sh`.
To build without,
`wasm-pack --target web`.
Both should be built to make sure the browser can fetch the one it needs.

On MPW side, the following headers should be set on the dev server:
```js
headers: {
	    "Cross-Origin-Embedder-Policy": "require-corp",
	    "Cross-Origin-Opener-Policy": "same-origin",	
}
```

Closes #27

### CODE REVIEW

**Review by panleone — COMMENTED** [review]
early review: multithreading is working really well impressive job! on my PC now it is something like x10 faster.

There are still some problems: some await are missing in pivx_shielding.js and on MPW spent notes are not removed from the list leading to errors

**Comment by panleone** [comment]
can you rebase this on master?

**Review by panleone — APPROVED** [review]
tACK  603f959e80fc74ca3e405689db437bbb2a830219
heavily tested:
On safari this with 31 spent notes took less than 3 minutes
https://testnet.rockdev.org/tx/b580f57f19a356ae27c23718933667c47a8d340f957d12ab2d61c81bd4d95638

On chromium this with 31 spent notes took about 5 minutes
https://testnet.rockdev.org/tx/0249e53e723306b11a57bf3150ec18943296891391c1d7afa2ca095c63d0e9be

Only one problem: note spent ONLY IN  s->t shield transaction  are not removed right after the tx is confirmed (in s->s everything works fine) but we can fix it in another PR

**Comment by Duddino** [comment]
Just a comment: Stable Safari does not support this because of this bug: https://bugs.webkit.org/show_bug.cgi?id=25212, which has already been fixed at least since November 2022 on Technology Preview

**Pull request merged**
